# Generated by Django 2.1 on 2018-09-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaobot', '0002_auto_20180829_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
